### ISSUE TITLE
Option to use a script?

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/cargo-bisect-rustc#11]
Is there an option to use a script like the old `bisect-rust`?

My use case was to test an incremental regression.  I had a simple one-line shell script which ran `cargo` twice, checking for specific behavior.  I don't see a way to do that with this tool.

**Comment by anp** [comment]
Are you able to use an `[alias]` section to your cargo config as described in [the cargo configuration docs](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys)?

**Comment by ehuss** [comment]
I don't think so, I needed to perform multiple steps to verify the bug, and failure of `cargo test` was the expected (correct) case.  It was something like: `cp src/foo_orig.rs src/foo.rs && cargo test && sleep 1 && cp src/foo_commented.rs src/foo.rs && cargo test && echo FNORD | rg -q FNORD`. 

I could write that as a rust test that spawned cargo itself, but a 1-line shell script is substantially easier.

(BTW, I'm willing to make a PR for this, I was just checking to see if it already existed or if the feature is even desired.)

**Comment by anp** [comment]
I just started looking through this codebase and was going to add an `--exec` flag but then realized the cargo arguments could cover my use case. I'm not sure who's reviewing PRs here these days, but it seems like a worthwhile feature to have to me.

**Comment by hellow554** [comment]
It would be very cool as well, if you can do something like [`git bisect`](https://git-scm.com/docs/git-bisect), namely provide a script which decides whether the build was good or bad (in my case, I can simply decide, based on the exit code of cargo).
