### ISSUE TITLE
More by-commit builds are available than what bisect-rustc wants to try

### ISSUE THREAD

**Issue by glandium** [rust-lang-nursery/cargo-bisect-rustc#18]
I had an old range of commits to bisect through, and bisect-rustc would tell me that they were all older than 90 days, but apparently, rustup-toolchain-install-master can find builds for them...

**Comment by Mark-Simulacrum** [comment]
Turns out we keep artifacts around for 168 days, not 90. I've updated the code to reflect this and pushed.
