### ISSUE TITLE
--start / --end don't seem to work

### ISSUE THREAD

**Issue by glandium** [rust-lang-nursery/cargo-bisect-rustc#3]
I tried passing various dates for --start/--end, but all I got was a search between the last two nightlies ("nightly-2018-03-21 through nightly-2018-03-22" as of writing).

Relatedly, it would be nice to be able to pass rust versions instead of nightly dates.

**Comment by kennytm** [comment]
@glandium Could you show some example inputs?

**Comment by glandium** [comment]
I've tried `--start nightly-2018-01-01`, `--start 2018-01-01`, and other dates.

**Comment by kennytm** [comment]
The correct format should be `--start 2018-01-01`. I'm checking why `--start 2018-01-01` won't work.

https://github.com/rust-lang-nursery/cargo-bisect-rustc/blob/328524bc615bd44de8187ab3de5ddb3357bd6816/src/main.rs#L130-L138

**Comment by glandium** [comment]
That function appears to return the right value for my input.

**Comment by glandium** [comment]
It looks like the `bisect_nightlies` code completely ignores the arguments.

```rust
   let mut nightly_date = today;
   let mut jump_length = 1;
   // before this date we didn't have -std packages
   let end_at = chrono::Date::from_utc(
       chrono::naive::NaiveDate::from_ymd(2015, 10, 20),
       chrono::Utc,
   );
```
