### ISSUE TITLE
Add an interactive mode

### ISSUE THREAD

**Issue by glandium** [rust-lang-nursery/cargo-bisect-rustc#9]
In some cases, like performance regression, it's hard to write reliable automated tests to drive the bisection. It would be great to have a git-bisect like interactive mode allowing to run commands manually and then tag whether the tested version was good or bad.

**Comment by est31** [comment]
Good example of something hard to automate is https://github.com/rust-lang/rust/issues/49336 ... I guess I have to resort to using rustup for this.
